steps:
  - id: 'build-server'
    name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'gcr.io/$PROJECT_ID/$REPO_NAME/server:$COMMIT_SHA',
        '-t',
        'gcr.io/$PROJECT_ID/$REPO_NAME/server:production',
        '-f',
        'Dockerfile.server',
        '.',
      ]
  - id: 'push-server'
    name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/$REPO_NAME/server:production']
    waitFor: ['build-server']

  - id: 'deploy-server'
    name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'run',
        'deploy',
        'portfolio-server',
        '--image',
        'gcr.io/$PROJECT_ID/$REPO_NAME/server:production',
        '--region',
        'us-central1',
        '--platform',
        'managed',
        '--project',
        '$PROJECT_ID',
      ]
    waitFor: ['push-server']

  - id: 'build-subscribers'
    name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'gcr.io/$PROJECT_ID/$REPO_NAME/subscribers:$COMMIT_SHA',
        '-t',
        'gcr.io/$PROJECT_ID/$REPO_NAME/subscribers:production',
        '-f',
        'Dockerfile.subscribers',
        '.',
      ]
  - id: 'push-subscribers'
    name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/$REPO_NAME/subscribers:production']
    waitFor: ['build-subscribers']
  - id: 'deploy-subscribers'
    name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'run',
        'deploy',
        'portfolio-subscribers',
        '--image',
        'gcr.io/$PROJECT_ID/$REPO_NAME/subscribers:production',
        '--region',
        'us-central1',
        '--platform',
        'managed',
        '--project',
        '$PROJECT_ID',
      ]
    waitFor: ['push-subscribers']

  - id: 'build-cron'
    name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'gcr.io/$PROJECT_ID/$REPO_NAME/cron:production',
        '-f',
        'Dockerfile.cron',
        '.',
      ]
  - id: 'push-cron'
    name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/$REPO_NAME/cron:production']
    waitFor: ['build-cron']
